# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73bc1149519846fa3a35d3acd6388b488b0faa0ec90f5aacc5a26de378e677ebc685b08ddc8855ddb3159a0265189fbfa9d3e6f59c46525936023df3a88f5b49

test:
  secret_key_base: 692b12273996ea54d232abea654f65b035d48f154757b0a5620a50df13649facbd23a3e86a05fe66618b7a47ad33f19560567d8cceaff1a84c131da9baf8ee20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
